//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Horarios_CIES.Models.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class HorarioDocente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HorarioDocente()
        {
            this.HorarioGrupo = new HashSet<HorarioGrupo>();
        }
    
        public long Id_HorarioDocente { get; set; }
        public long Id_Materia { get; set; }
        public long Id_Docente { get; set; }
        public string Ciclo { get; set; }
        public string Dia { get; set; }
        public string Hora_Inicio { get; set; }
        public string Hora_Fin { get; set; }
    
        public virtual Docente Docente { get; set; }
        public virtual Materia Materia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HorarioGrupo> HorarioGrupo { get; set; }
    }
}
