//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Horarios_CIES.Models.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class HorarioGrupo
    {
        public long Id { get; set; }
        public long Id_Grupo { get; set; }
        public long Id_Materia { get; set; }
        public long Id_Ciclo { get; set; }
    
        public virtual Ciclos Ciclos { get; set; }
        public virtual Grupo Grupo { get; set; }
        public virtual Materia Materia { get; set; }
    }
}
