//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Horarios_CIES.Models.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class HorarioDocente
    {
        public long Id_HorarioDocente { get; set; }
        public long Id_Materia { get; set; }
        public long Id_Docente { get; set; }
        public string Ciclo { get; set; }
        public string Dia { get; set; }
        public string Hora_Inicio { get; set; }
        public string Hora_Fin { get; set; }
        public long Id { get; set; }
    
        public virtual Docente Docente { get; set; }
        public virtual Materia Materia { get; set; }
    }
}
